list=['mom','dad','uncle']
print (list)
print(list[0] +',  You are invited to my party')
print(list[1] +',  You are invited to my party')
print(list[2] +',  You are invited to my party')
print('I found a bigger dining table!')
list.insert(0,'greatgrandma')
list.insert(2,'greatgrandpa')
list.append('ghost')
print(list)
print(list[0] +',  You are invited to my party')
print(list[1] +',  You are invited to my party')
print(list[2] +',  You are invited to my party')
print(list[3] +',  You are invited to my party')
print(list[4] +',  You are invited to my party')
print(list[5] +',  You are invited to my party')
