list=['mom','dad','uncle']
print (list)
print(list[0] +',  You are invited to my party')
print(list[1] +',  You are invited to my party')
print(list[2] +',  You are invited to my party')
print('I found a bigger dining table!')
list.insert(0,'greatgrandma')
list.insert(2,'greatgrandpa')
list.append('ghost')
print(list)
print(list[0] +',  You are invited to my party')
print(list[1] +',  You are invited to my party')
print(list[2] +',  You are invited to my party')
print(list[3] +',  You are invited to my party')
print(list[4] +',  You are invited to my party')
print(list[5] +',  You are invited to my party')
print('I can actually invite 2 more people to my dinner :(')
listi = list.pop(0)
print('I am sorry, '+ listi + '.')
listo = list.pop(1)
print('I am sorry, '+ listo + '.')
lista = list.pop(2)
print('I am sorry, '+ lista + '.')
listy = list.pop(0)
print('I am sorry, '+ listy + '.')
print(list)
print('You are still invited! '+ list[0])
print('You are still invited! '+ list[1])
del list[0]
del list[0]
print(list)
